package dateInfoTBApi

const (
	VOCATION_ZH_CN  = "VOCATION_ZH_CN"
	VOCATION_ZH_HK  = "VOCATION_ZH_HK"
	VOCATION_ZH_TW  = "VOCATION_ZH_TW"
	VOCATION_ZH_MAC = "VOCATION_ZH_MAC"
	FESTIVAL_ZH_CN = "Festival_ZH_CN"
	FESTIVAL_ZH_HK = "Festival_ZH_HK"
	FESTIVAL_ZH_TW = "Festival_ZH_TW"
	FESTIVAL_ZH_MAC = "Festival_ZH_MAC"
)